name: Node.js CI

on:
  push:
    branches: 
      - main
    paths:
      - demo-app/**
  pull_request:
    branches: 
      - main
    paths:
      - demo-app/**
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x.x
      - name: Build with dotnet
        run: dotnet build --configuration Release demo-app/ThinnesenApi/ThinnesenApi.csproj
      - name: Test with dotnet
        run: dotnet test --configuration Release --no-build demo-app/ThinnesenApi.Tests/ThinnesenApi.Tests.csproj
    
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: thinnesen/tradingaps_production_demoapp:${{ github.run_number }}
          file: demo-app/Dockerfile
          working-directory: ./demo-app

#      - name: Repository Dispatch
#        uses: peter-evans/repository-dispatch@v1
#        with:
#          token: ${{ secrets.GIT_PAT }}
#          repository: thinnesen/tradingaps-manifest
#          event-type: new-image-production_demoapp
#          client-payload: '{"image": "thinnesen/tradingaps_production_demoapp:${{ github.run_number }}"}'  