name: Node.js CI

on:
  push:
    branches: 
      - main
    paths:
      - demo-app/**
  pull_request:
    branches: 
      - main
    paths:
      - demo-app/**
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x.x
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Test with dotnet
        run: dotnet test --configuration Release --no-build