name: Node.js [Build_Test]

on:
  push:
    branches: 
      - '**'
    paths:
      - demo-app/**
  pull_request:
    branches: 
      - 'main'
    paths:
      - demo-app/**

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x.x
      - name: install-dependencies
        run: dotnet restore demo-app/ThinnesenApi/ThinnesenApi.csproj
      - name: Build with dotnet
        run: dotnet build --configuration Release demo-app/ThinnesenApi/ThinnesenApi.csproj
      - name: Test with dotnet
        run: dotnet test --configuration Release --no-build demo-app/ThinnesenApi.Tests/ThinnesenApi.Tests.csproj

      - name: Repository Dispatch
     #   if: github.event.pull_request.merged
        uses: peter-evans/repository-dispatch@v1
        with:
          event-type: test_succeeded
        #  client-payload: '{"greet": "${{ steps.maybe-greet.outputs.GREET }}"}'


