name: ci_website

on:
  push:
    branches: 
      - main
    paths:
      - website-app/**
  pull_request:
    branches: 
      - main
    paths:
      - website-app/**

  workflow_dispatch:
env:
  IMAGE_NAME: tradingaps_production
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: thinnesen/website-tradingaps:${{ github.run_number }}
        file: website-app/dockerfile

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GIT_PAT }}
        repository: thinnesen/tradingaps-manifest
        event-type: new-image-production
        client-payload: '{"image": "thinnesen/website-tradingaps:${{ github.run_number }}"}'
