name: Node.js [Dockerhub]

on:
  repository_dispatch:
    types: [test_succeeded]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: thinnesen/application-tradingaps:${{ github.run_number }}
          file: demo-app/Dockerfile
          working-directory: ./demo-app

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GIT_PAT }}
          repository: thinnesen/tradingaps-manifest
          event-type: new-image-production_demoapp
          client-payload: '{"image": "thinnesen/application-tradingaps:${{ github.run_number }}"}'  




